language: go
sudo: false
go:
  - 1.9.x
  - 1.8.x
  - 1.7.x
  - 1.6.x
  - 1.5.x
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
